### ISSUE TITLE
Missing META-INF/services/javax.annotation.processing.Processor in 6.0 apt jar file

### ISSUE THREAD

**Issue by aspan** [OpenFeign/querydsl#223]
The file `META-INF/services/javax.annotation.processing.Processor` is missing from the jar files in `querydsl-apt-6.0.0.M3.jar` it is there in version 5.1.1. In 5.1.1 and earlier versions the annotation processor was auto detected by the maven compiler plugin but now it has to be specified with
```
<annotationProcessors>
  <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
</annotationProcessors>
```

**Comment by velo** [comment]
Thanks for the feedback @aspan 

I'm traveling for a week, and I won't be able to address it until I'm back.

Feel free to raise a PR if you able to.

Cheers

**Comment by aspan** [comment]
I investigated further and noticed that there are multiple jar files published with different classifiers depending on which annotation processor you want. Previously the JPA variant was published as the jar without classifier. I think that the current situation is better. If using the jar without classifier you have to specify the annotation processors you want. If you are only using one specific annotation processor specify your dependency like this instead
```
    <dependency>
      <groupId>io.github.openfeign.querydsl</groupId>
      <artifactId>querydsl-apt</artifactId>
      <version>6.0.0.M3</version>
      <classifier>jpa</classifier>
    </dependency>
```

**Comment by aspan** [comment]
Issue is resolved by configuring the dependency correctly.
