### ISSUE TITLE
Could give an example for multi data source for query dsl sql codegen?

### ISSUE THREAD

**Issue by nikbobo** [OpenFeign/querydsl#228]
I want to use query dsl sql in spring, but we using multi data source in application.
```
<configuration>
    <jdbcDriver>org.apache.derby.jdbc.EmbeddedDriver</jdbcDriver>
    <jdbcUrl>jdbc:derby:target/demoDB;create=true</jdbcUrl>
    <packageName>com.myproject.domain</packageName>
    <targetFolder>${project.basedir}/target/generated-sources/java</targetFolder>
</configuration>
```
So this example not suitable for me, I want to generator multi data source in application like mybatis generator.

**Comment by velo** [comment]
You would need multiple executions, one for each database

https://maven.apache.org/guides/mini/guide-configuring-plugins.html#using-the-executions-tag
