### ISSUE TITLE
thank you for queryDSL

### ISSUE THREAD

**Issue by yanghuilong** [OpenFeign/querydsl#237]
thank you for queryDSL

**Comment by velo** [comment]
All good, just trying to keep a good project alive.

Feel free to support this endeavor

https://github.com/sponsors/velo

**Comment by totof3110** [comment]
Thanks for keeping querydsl alive!

**Comment by weir2010** [comment]
非常棒

**Comment by vulinh64** [comment]
My thanks to the OpenFeign for keeping my favorite library alive!

**Comment by velo** [comment]
Sponsoring is the most sincere compliment.
