### ISSUE TITLE
[Question] Why the APT Code generation process is needed ?

### ISSUE THREAD

**Issue by xGreenNarae** [OpenFeign/querydsl#250]
Hello,
I've been studying Querydsl's source code for a few days, and I've come to a question and I'd like to ask you a question!

Currently, Querydsl relies on Hibernate's Query interface and also includes the creation of QClass files at build time.
(A rough look at other similar libraries also showed that there must be an additional build-time code generation process.)

However, looking at ORMs such as Kotlin's Exposed, I found that there are technologies that do not include the code generation process separately and rely on JPA EntityManager's [create query](https://jakarta.ee/specifications/persistence/2.2/apidocs/javax/persistence/entitymanager#createQuery(java.lang.String,java.lang.Class)) method rather than Hibernate.

In Querydsl, I thought that it would be easier to process without the code generation process if I used the create query method by reading and parsing the information of the entity and its fields using the Reflection API.

Is there something I'm missing? 
(maybe it's because of the fundamental difference between java and kotlin that I don't know...?)

I'd like you to tell me why the APT code generation process is necessary in Querydsl ! 😃

**Comment by velo** [comment]
By using reflection there would be no compile time check, leading to runtime errors.

If you happy with runtime errors, writing HQL by hand should do just fine =)
