### ISSUE TITLE
Q-Classes are generated , Did not find type  PK in org.learn.domain.entity.gms.BaseEntity<? extends java.io.Serializable> for org.learn.domain.entity.gms.IntimeProductInfo

### ISSUE THREAD

**Issue by yanghuilong** [OpenFeign/querydsl#259]
![image](https://github.com/OpenFeign/querydsl/assets/10112138/f96a535c-f7d9-4df4-a169-400762620468)

**Comment by velo** [comment]
Can I have an simple example that I can run locally that demonstrates the issue?

Alternatively, you can grant me access to your company repository 🤩
