### ISSUE TITLE
Support query delegates on collection classes

### ISSUE THREAD

**Issue by edudar** [OpenFeign/querydsl#260]
Originally filed as https://github.com/querydsl/querydsl/issues/3327

`@QueryDelegate` is a powerful feature that does not work properly with collections. QueryDSL creates Q-classes, but they extend `BeanPath`. As a result, one can't use expressions already available in these classes and can't pass appropriately typed `Path` parameters to custom extensions.

Actual:
```
public class QSet extends BeanPath<Set<?>> {
  ...
}
```

Expected:
```
public class QSet<V, E extends SimpleExpression<V>> extends SetPath<V, E> {
  ...
} 

public class QEntity extends BeanPath<Entity> {
  public final QSet<String, ext.java.lang.QString> s = 
    new QSet<String, ext.java.lang.QString>(forProperty("s"));
}
```

I tried to tinker around the annotation processor, but it does not look like it generally supports the generation of parameterized classes.

**Comment by velo** [comment]
Seems no one is working on this, I'm closing to clear the board.  Feel free to reopen after a PR is submitted.
