### ISSUE TITLE
About this fork!

### ISSUE THREAD

**Issue by lefou** [OpenFeign/querydsl#274]
First, thanks you for maintaining this great library.

Can you please, if possible, create this project as a fork to the [official querydsl](https://github.com/querydsl/querydsl) project? This makes this project more discoverable. It also help in comparing changes and finding open issues. (Maybe, this requires to delete or rename it, and create a fork, than push your changes again.)

In the readme, you say, that the querydsl project is not interested in your maintenance. Do you have any links?

**Comment by danielvion** [comment]
There was little to no interest from the maintainers to cooperate and help bring the library up to date. Check out the conversations there. The trigger for this fork was the incompatibilities with Jakarta and Hibernate 6. They just more or less refused to address it.

https://github.com/querydsl/querydsl/issues/3562
https://querydsl.slack.com/archives/C06KLG1BP/p1698220668765159

https://github.com/querydsl/querydsl/issues/3543
https://github.com/spring-projects/spring-boot/issues/38189

**Comment by velo** [comment]
Hi @lefou 

This originally was a fork.

But then every pull request I need to pick a fork, so I undo the forking and won't be introducing that extra complexity again.  Sorry for any inconveniences.

**Comment by lefou** [comment]
Thank you for the response. Personally, if find the argument a bit thin, but since the slack chats are not public (at least not without creating an account), I probably don't see the whole picture here.

Being a maintainer of many open source projects myself, let me add, that from a maintainer perspective, there was no strong sign of help. I can see reports and requests. And also a vague  comment, offering some help. But there were no recent pull requests, not a single one trying to fix one of the pressing issues, and also no request for being added to the maintainer group. I wouldn't count this as "not being interested". Hence, from what I can see, a fork is a real surprise. 

It's not necessarily the job of the project maintainer to fix all issues alone. The job is to maintain the project, keep tool chains running, review pull requests, help new contributors and steer the overall direction. 

> This originally was a fork.
> 
> But then every pull request I need to pick a fork, so I undo the forking and won't be introducing that extra complexity again. Sorry for any inconveniences.


Think about the much larger inconvenience all the existing users and watchers face, since this is now a decoupled repository. _tabula rasa._ A mature code base without a backlog of issues.

**Comment by velo** [comment]
> Thank you for the response. Personally, if find the argument a bit thin, but since the slack chats are not public (at least not without creating an account), I probably don't see the whole picture here.

In short, I offered help, and answer was there is no value on merging dependabot PRs. And what they need was a documentation writer/Gradle plugin author.

For a project stale for 2 years, even a release that just bump the Java version adds value.


> Being a maintainer of many open source projects myself, let me add, that from a maintainer perspective, there was no strong sign of help. I can see reports and requests. And also a vague comment, offering some help. But there were no recent pull requests, not a single one trying to fix one of the pressing issues, and also no request for being added to the maintainer group. I wouldn't count this as "not being interested". Hence, from what I can see, a fork is a real surprise.

I maintain feign mostly by myself since 2018, and strongly involved in opensource projects even before GitHub was a thing. Querydsl was at best stale.

I offered to help on slack, and was told they don't need it.

I'm posting all the releases, news and updates on querydsl team official slack channel, not once someone shown any interest in getting help either

> 
> It's not necessarily the job of the project maintainer to fix all issues alone. The job is to maintain the project, keep tool chains running, review pull requests, help new contributors and steer the overall direction.

I completely agree. I will not work on issues that do not directly affect me. But plenty already join this initiative and offered a helping hand. Which is they way to go as I focus more on releasing and guidance, but less coding.

> Think about the much larger inconvenience all the existing users and watchers face, since this is now a decoupled repository. _tabula rasa._ A mature code base without a backlog of issues.

I don't have any alternative to offer here. It's either inconvenient to the people working in the project or to the people using it.

At the end of the day, the issues there are stale and any new issues there wouldn't spark my attention either.

Feel free to port any issues that you feel are relevant.

**Comment by lefou** [comment]
Thanks for the clarifications. I hope you don't feel offended by my messages. I was curious, what's behind the fork. Tradeoffs need to be made. I wish you an the project the best.

**Comment by velo** [comment]
Going to save the original offer here, as slack will delete history over time:

> Hello team,
>
> Seems querydsl is a bit abandoned and need a caretaker to help out. I would like to help out.
I took a caretaker role for https://github.com/OpenFeign/feign, my main role there has been keep PRs going, keep dependencies up to date and getting releases out of the door so people can still use the project.
> 
> I would love to do the same for querydsl, can I? Please?

![image](https://github.com/OpenFeign/querydsl/assets/136590/d9f1d4fb-a941-421f-b1c6-16c3452b4a49)

**Comment by lefou** [comment]
Looks like some miscommunication to me. They welcomed you, especially if your help is about "improving documentation, creating PR's". The latter is exactly what you were looking for, I think. The former it a logical consequence. 

About merging dependabot PRs. Especially for JVM libraries, there is often not much value in bumping dependencies, quite the contrary, as you risk to loose support for older versions just by the fact that you are not building / testing against them. Of course, you can comment and close dependabot PRs, but I also caught myself with just ignoring them on less important projects. That does not mean I don't recognized and evaluated them, but it's extra work, often irrelevant, when the PRs gets auto-closed by the next version bump.

**Comment by velo** [comment]
Leaving the dependabots PRs there is fine (well, kinda, there were security issues on some).

But the are other 9 (more actually) sitting there left to rot.  Useful things, and all easy to merge, as people behind them already submitted most here. So creating more PR's wouldn't solve much.

As I said on my readme, I'm happy to merge this changes to source repo and archive mine.  But there is nobody active on querydsl/querydsl, or they would have noticed the many comments on issues to move this way or my posts on slask about releasing 5.2, 6.0....

Code is untouched for 2 years, and last release is about to turn 3

**Comment by velo** [comment]
BTW, if you know someone willing to take all that was done back to the original project and get it alive again, feel free to speak on my behalf.

**Comment by odrotbohm** [comment]
Just FYI: Querydsl 5.1 [was just released](https://github.com/querydsl/querydsl/tree/QUERYDSL_5_1_0).

**Comment by velo** [comment]
Mission accomplished! I hope.

Now there is just a 2 year of pull requests to review and merge
