### ISSUE TITLE
Has QueryDSL started maintenance?

### ISSUE THREAD

**Issue by leshalv** [OpenFeign/querydsl#277]
I see version 5.1.0 was released yesterday,https://github.com/querydsl/querydsl/releases/tag/QUERYDSL_5_1_0

**Comment by danielvion** [comment]
We are trying to figure out if we can merge this fork to the main repository. We are waiting for feedback from the maintainers at the moment.

**Comment by velo** [comment]
> Has QueryDSL started maintenance? 

Don't know.  Seems this project managed to rock the boat enough to get one release out.

Now we asked they maintainers what they want to do, but haven't heard back.

**Comment by leshalv** [comment]
At the moment, it's just a bunch of dependencies that have been upgraded, and nothing else seems to have changed

**Comment by velo** [comment]
Well, it's a start. Getting a project that is dormant for 3 years moving again it's not trivial.

Let's hope we can get all the changes done here merged back on the original project.

**Comment by murainwood** [comment]
> At the moment, it's just a bunch of dependencies that have been upgraded, and nothing else seems to have changed↳

yes, only some dependencies upgrading...

**Comment by velo** [comment]
Well, a conversation was started.... but I honestly have no idea if the changes here will make into original project.

**Comment by leshalv** [comment]
Have you been in contact with them?

**Comment by velo** [comment]
Yes, conversations been slow, and I'm not sure which way is going.

This fork made enough waves to caught attention.

**Comment by leshalv** [comment]
The project has been sleeping for too long, I don't agree with their so-called stable software, there are many problems at the moment, and the new hibernate features are not compatible.

**Comment by velo** [comment]
Well, I did what I could. Let's see where it goes

**Comment by velo** [comment]
Seems nothing changed
