### ISSUE TITLE
R2DBC connection not released back to the pool

### ISSUE THREAD

**Issue by mozguletz** [OpenFeign/querydsl#352]
Existing implementation of `AbstractR2DBCQuery.fetch()` and `unsafeCount()` takes an existing connection from the connection provider and uses it, in case if a connection pool is used, the connections are never closed

`return getConnection()
        .flatMapMany(
            conn -> { ...});
`

A way to handle the close connection (returning it to the pool)

`return Flux.usingWhen(getConnection(), 
            conn -> { ...},
            Connection::close);
`

Is there a way to close the connection from the connection provider in case if a connection pool is used?

**Comment by velo** [comment]
@mozguletz uuuups.

My bad.

Are you able to submit a pull request fixing it?


Cheers

**Comment by xeounxzxu** [comment]
@velo @mozguletz I'll try to fix it.

**Comment by velo** [comment]
Seems no one is working on this, I'm closing to clear the board.  Feel free to reopen after a PR is submitted.

**Comment by madebyearth** [comment]
Is anyone working on this?
