### ISSUE TITLE
Gradle working example

### ISSUE THREAD

**Issue by fab918** [OpenFeign/querydsl#357]
Hello,

I spent a few hours trying to get a project running with this version of QueryDSL. My project basically works with queryDsl v4. I'd like to update it, but I've tried everything I can't found on the Internet but and I can't get my Q classes generated with V5 and grandle. The examples on the repo are in Maven only unfortunately.

Is it possible to get help to have a minimal project that generates Q classes with Gradle?

I think it will help other people. Thanks for everything!

**Comment by velo** [comment]
@fab918  we need to create a gradle plugin for querydsl.

But I never got to make one.

If you keen on making it happen, I'm more than happy to review and advise.

This might be a good inspiration
https://github.com/jOOQ/jOOQ/blob/main/jOOQ-codegen-gradle/src/main/java/org/jooq/codegen/gradle/NamedConfiguration.java

**Comment by fab918** [comment]
@DaiYuANg It doesn't work, nothing happens when I run a build with gradle, normally the classes should be generated.

I tried :

```
compileOnly("io.github.openfeign.querydsl:querydsl-apt:${libs.versions.queryDsl.get()}:jpa")
annotationProcessor("io.github.openfeign.querydsl:querydsl-apt:${libs.versions.queryDsl.get()}:jpa")
```

I've tried the suggested configuration here https://github.com/OpenFeign/querydsl/issues/357, in the same way, nothing happens when I build. 

 I tested with java 17 and 21.

```
  implementation("io.github.openfeign.querydsl:querydsl-core:$queryDslVersion")
  implementation("io.github.openfeign.querydsl:querydsl-jpa:$queryDslVersion")
  annotationProcessor("io.github.openfeign.querydsl:querydsl-apt:$queryDslVersion:jpa")
  annotationProcessor("jakarta.persistence:jakarta.persistence-api")
  annotationProcessor("jakarta.annotation:jakarta.annotation-api")
```

@velo  Why should we need a plugin to run the library on Gradle?

**Comment by vidakovic** [comment]
@fab918 ... I am using:

```
annotationProcessor "com.infobip:infobip-spring-data-jdbc-annotation-processor"
```

Note: the latest version 9.0.7 is not compatible, but I've created a PR to move all dependencies from "com.querydsl:*" to "io.github.openfeign.querydsl:*" https://github.com/infobip/infobip-spring-data-querydsl/pull/101.

**Comment by lucasdistasi** [comment]
Any updates on this? I'm using Kotlin and Gradle and Q classes are not being generated.

**Comment by velo** [comment]
Needs someone to take charge in this initiative. I don't have the bandwidth

**Comment by konczdam** [comment]
@lucasdistasi I managed to make it generate the Q classes in a project with Spring Boot, Kotlin Entity classes and Kotlin Gradle file.

```kts
plugins {
    val kotlinVersion = "2.0.0"
    kotlin("jvm") version kotlinVersion
    kotlin("plugin.spring") version kotlinVersion
    kotlin("plugin.jpa") version kotlinVersion
    kotlin("kapt") version kotlinVersion

    id("org.springframework.boot") version "3.2.5"
    id("io.spring.dependency-management") version "1.1.4"
}

dependencies {
    val querydslVersion = "6.7"
    implementation("io.github.openfeign.querydsl:querydsl-jpa:$querydslVersion")
    implementation("io.github.openfeign.querydsl:querydsl-sql:$querydslVersion")

    kapt("io.github.openfeign.querydsl:querydsl-apt:$querydslVersion")
    compileOnly("io.github.openfeign.querydsl:querydsl-apt:$querydslVersion:jpa")
}

kapt {
    arguments {
        arg("querydsl.entityAccessors", "true")
    }
}
sourceSets {
    main {
        kotlin {
            srcDir("src/main/kotlin")
        }
    }
    test {
        kotlin {
            srcDir("src/test/kotlin")
        }
    }
}
```

It generates the Q classes to the `build/generated/source/kapt/main` folder.
To run the class generation, run either of these:
```sh
gradle kaptKotlin
gradle build
```

Hope this helped.

**Comment by velo** [comment]
Seems no one is working on this, I'm closing to clear the board.  Feel free to reopen after a PR is submitted.
