### ISSUE TITLE
Re-open method SqlQuery#Q from(Expression<?> arg) as public

### ISSUE THREAD

**Issue by ulk200** [OpenFeign/querydsl#360]
I used to be able to set _FROM_ with basic "Expression<?>" objects. 

In ProjectableSQLQuery
```
public Q from(Expression<?> arg) {
  return queryMixin.from(arg);
}
````

But with the fix from issue https://github.com/OpenFeign/querydsl/pull/251 this signature has been made `protected`.
My main usage is calling it with Template expressions with Oracle's procedure call, generating an sql like `SELECT ... FROM TABLE(PROCEDURE(...)) a` by passing `Expression.template(Tuple.class, "TABLE(PROCEDURE(...)")` to the method.

Maybe i'm missing something and this can translated to a RelationalPath ? (because is see that `from(RelationalPath<?> arg)` is supposed to be the new way of setting the from expression)

I'm using QueryDSL SQL without JPA BTW

**Comment by velo** [comment]
Feel free to send a PR, I will review
