### ISSUE TITLE
What is the compatibility of QueryDSL <> Hibernate?

### ISSUE THREAD

**Issue by Plondrein** [OpenFeign/querydsl#406]
I have an application that uses JDK 21, Spring Boot 2.7 and Hibernate 5.4 - it doesn't seem to be supported by QueryDSL 6+ . 
Am I correct and if yes, is it ok if I cherry-pick recent change to 5.X (https://github.com/OpenFeign/querydsl/pull/388) ?

**Comment by velo** [comment]
Querydsl 6 is Spring boot 3, hibernate 6 and jakarta.* compatible.

For Springboot 2, hibernate 5 and javax.* projects you will be limited to querydsl 5.2.

If you need any new functionality from 6.x on 5.x, you gonna need raise a PR cherry-picking the change.
