### ISSUE TITLE
On JDK 21, error: The reference to StringTemplate is ambiguous.

### ISSUE THREAD

**Issue by imhansai** [OpenFeign/querydsl#476]
**Problem Description:**

In jdk21, if the following code snippet is used:
```
import com.querydsl.core.annotations.QueryDelegate;
import com.querydsl.core.types.dsl.Expressions;
import com.querydsl.core.types.dsl.SimpleExpression;
import com.querydsl.core.types.dsl.StringTemplate;

public class QueryExtensions {

  @QueryDelegate(String.class)
  public static StringTemplate gc(SimpleExpression<String> expression) {
    return Expressions.stringTemplate("group_concat({0})", expression);
  }
}

```
An error will occur: Ambiguous reference to StringTemplate

**Source code analysis:**

The location of the relevant source code to generate the Q class is:
https://github.com/OpenFeign/querydsl/blob/d526c2f9a086cd6e587837636bf9af9c6963f3d5/querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/DefaultEntitySerializer.java#L467-L534

Especially this line of code:
https://github.com/OpenFeign/querydsl/blob/d526c2f9a086cd6e587837636bf9af9c6963f3d5/querydsl-tooling/querydsl-codegen/src/main/java/com/querydsl/codegen/DefaultEntitySerializer.java#L487-L488

The code it generates is:
```
import com.querydsl.core.types.dsl.*;
```
but missing `com.querydsl.core.types.dsl.StringTemplate`

**Possible solutions:**

Add after line 488:
```
// com.querydsl.core.types.dsl.StringTemplate
writer.importClasses("com.querydsl.core.types.dsl.StringTemplate");
```

The generated code will be:
```
import com.querydsl.core.types.dsl.*;

import com.querydsl.core.types.dsl.StringTemplate;
```

**Comment by velo** [comment]
Ah, mano, se pah se pega junto, se pah naum rola tah ligado

**Comment by imhansai** [comment]
Sorry, I don't quite understand what you mean. Could you explain it in more detail? Thanks:)

**Comment by SightStudio** [comment]
@imhansai looks like he wants you to use English
I don't know what you want either, even with Google translator

**Comment by imhansai** [comment]
@velo @SightStudio I described the problem in English and gave possible solutions. Please take a look and see if you can understand my intention?

**Comment by velo** [comment]
Your issue is probably related to this:
https://github.com/querydsl/querydsl/pull/3596/files#diff-fd4e54bf628753199510a30dfabc22e20e5d3a80e115fd98888583d90c53e46aR20


Seems the solution you recommending is correct:
```
writer.importClasses("com.querydsl.core.types.dsl.StringTemplate");
```

Can you raise a PR?

I will merge and make a dot release today if you can send me a PR

**Comment by imhansai** [comment]
Ok, I'll send a PR later. :)
