### ISSUE TITLE
QueryDSL 6.7+ Compatibility with Spring Boot

### ISSUE THREAD

**Issue by Mouon** [OpenFeign/querydsl#600]
I want to start by expressing my heartfelt thanks for your dedication and hard work in maintaining QueryDSL. Your efforts are greatly appreciated by the entire community.

I have a suggestion that I hope you might consider: it would be fantastic if QueryDSL versions 6.7 and above could achieve official compatibility with Spring Boot. This improvement could be highly beneficial for many users who integrate these technologies.

Additionally, if a professional profile image were added to the project, I believe it would help other developers more easily recognize that this project continues the work of QueryDSL.

If there are any ways I can assist with this effort or contribute to making this enhancement possible, please let me know. Thank you once again for your commitment and for considering this suggestion.

**Comment by velo** [comment]
> I want to start by expressing my heartfelt thanks for your dedication and hard work in maintaining QueryDSL. Your efforts are greatly appreciated by the entire community.

Thanks

> I have a suggestion that I hope you might consider: it would be fantastic if QueryDSL versions 6.7 and above could achieve official compatibility with Spring Boot. This improvement could be highly beneficial for many users who integrate these technologies.

Feel free to send a PR, I will review, merge and release ASAP.  But I don't need it for my job, so I won't work for on it.

> Additionally, if a professional profile image were added to the project, I believe it would help other developers more easily recognize that this project continues the work of QueryDSL.

Happy to add one if anyone provides one.  As mentioned on the readme, I only do things that affect my daytime job (in other works, were someone pays me to do it)

> If there are any ways I can assist with this effort or contribute to making this enhancement possible, please let me know. Thank you once again for your commitment and for considering this suggestion.

Well, anything you want to do, I'm happy to take.  Happy to take you onboard of the project if you actively working on it.

**Comment by velo** [comment]
I'm closing this as I have no plans of working on this, but feel free to reopen if/when you get any of these started
